KerasH5:   resnet_v1_eembc/model_best.h5
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xc7z020clg400-1
ClockPeriod: 10
Backend: Vivado

IOType: io_stream
HLSConfig:
  Model:
    Precision: ap_fixed<8,4>
    ReuseFactor: 2304
    Strategy: Resource
