save_dir: resnet_v1_eembc_tiny

model:
  name: resnet_v1_eembc_tiny
  filters: 
  - 2
  l1: 0
  l2: 1e-4
  kernels:
  - 1
  - 1
  strides:
  - 1
  - 2

pruning:
  sparsity: 1.0 

fit:
  compile:
    initial_lr: 0.001
    lr_decay: 0.99
    optimizer: Adam
    loss: categorical_crossentropy
  epochs: 200
  patience: 40
  batch_size: 32
  verbose: 1

convert:
  OutputDir: my-hls-test-tiny
  XilinxPart: xc7z020clg400-1
  Backend: Pynq
  IOType: io_stream
  Precision: ap_fixed<8,4>
  ReuseFactor: 64
  ClockPeriod: 20
  Strategy: Resource